# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twuckoo}
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Balint Erdi"]
  s.date = %q{2010-04-28}
  s.default_executable = %q{twuckoo}
  s.description = %q{      A simple yet elegant solution to tweet a message regularly from a file (or from a webpage, a database, etc.)
}
  s.email = %q{balint.erdi@gmail.com}
  s.executables = ["twuckoo"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/twuckoo",
     "lib/duration_string.rb",
     "lib/environments.rb",
     "lib/modules.rb",
     "lib/modules/one_line_from_file.rb",
     "lib/modules/wikipedia_tfa.rb",
     "lib/twuckoo.rb",
     "lib/twuckoo/config.rb",
     "lib/twuckoo/runner.rb",
     "spec/duration_string_spec.rb",
     "spec/one_line_from_file_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/twuckoo/config_spec.rb",
     "spec/twuckoo/runner_spec.rb",
     "spec/wikipedia_tfa_spec.rb",
     "tasks/spec.rake",
     "twuckoo.gemspec"
  ]
  s.homepage = %q{http://github.com/balinterdi/twuckoo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Need to tweet periodically in an automated fashion? Then Twuckoo is for you!}
  s.test_files = [
    "spec/duration_string_spec.rb",
     "spec/one_line_from_file_spec.rb",
     "spec/spec_helper.rb",
     "spec/twuckoo/config_spec.rb",
     "spec/twuckoo/runner_spec.rb",
     "spec/wikipedia_tfa_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.9.5"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<twibot>, [">= 0.1.7"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.6.164"])
      s.add_runtime_dependency(%q<mail>, [">= 1.6.0"])
      s.add_runtime_dependency(%q<tlsmail>, [">= 0.0.1"])
    else
      s.add_dependency(%q<mocha>, [">= 0.9.5"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<twibot>, [">= 0.1.7"])
      s.add_dependency(%q<hpricot>, [">= 0.6.164"])
      s.add_dependency(%q<mail>, [">= 1.6.0"])
      s.add_dependency(%q<tlsmail>, [">= 0.0.1"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.9.5"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<twibot>, [">= 0.1.7"])
    s.add_dependency(%q<hpricot>, [">= 0.6.164"])
    s.add_dependency(%q<mail>, [">= 1.6.0"])
    s.add_dependency(%q<tlsmail>, [">= 0.0.1"])
  end
end

