# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twuckoo}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Balint Erdi"]
  s.date = %q{2010-01-12}
  s.description = %q{      A simple yet elegant solution to tweet a message regularly from a file (from a webpage, a database, etc.)
}
  s.email = %q{balint.erdi@gmail.com}
  s.executables = ["edit_json.rb", "jeweler", "prettify_json.rb", "rubyforge", "t4rsh", "twuckoo"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "Gemfile",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/edit_json.rb",
     "bin/prettify_json.rb",
     "bin/t4rsh",
     "bin/twuckoo",
     "lib/duration_string.rb",
     "lib/environments.rb",
     "lib/modules.rb",
     "lib/modules/one_line_from_file.rb",
     "lib/modules/wikipedia_tfa.rb",
     "lib/twuckoo.rb",
     "lib/twuckoo/config.rb",
     "lib/twuckoo/runner.rb",
     "spec/duration_string_spec.rb",
     "spec/one_line_from_file_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/twuckoo/config_spec.rb",
     "spec/twuckoo/runner_spec.rb",
     "spec/wikipedia_tfa_spec.rb",
     "tasks/spec.rake",
     "twuckoo.gemspec",
     "vendor/gems/environment.rb",
     "vendor/gems/ruby/1.8/cache/activesupport-2.3.5.gem",
     "vendor/gems/ruby/1.8/cache/hpricot-0.8.2.gem",
     "vendor/gems/ruby/1.8/cache/json-1.2.0.gem",
     "vendor/gems/ruby/1.8/cache/mail-1.5.2.gem",
     "vendor/gems/ruby/1.8/cache/mbbx6spp-twitter4r-0.4.0.gem",
     "vendor/gems/ruby/1.8/cache/mime-types-1.16.gem",
     "vendor/gems/ruby/1.8/cache/twibot-0.1.7.gem"
  ]
  s.homepage = %q{http://github.com/balinterdi/twuckoo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Need to tweet periodically in an automated fashion? Then Twuckoo is for you!}
  s.test_files = [
    "spec/duration_string_spec.rb",
     "spec/one_line_from_file_spec.rb",
     "spec/spec_helper.rb",
     "spec/twuckoo/config_spec.rb",
     "spec/twuckoo/runner_spec.rb",
     "spec/wikipedia_tfa_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

